version: "1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogapi-app
    environment:
      DB: ${DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      MY_SECRET_KEY: ${MY_SECRET_KEY}
    env_file:
      - .env
    networks:
      - blogapi-network
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15.1
    container_name: blogapi-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    expose:
      - '5432'
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - blogapi-pg-data:/var/lib/postgresql/data
    networks:
      - blogapi-network
    command: -p 5432

volumes:
  blogapi-pg-data:

networks:
  blogapi-network: